post-checkout:
  commands:
    configure-git:
      run: git config blame.ignoreRevsFile .git-blame-ignore-revs

pre-commit:
  parallel: true
  commands:
    tsc:
      glob: "*.{ts,tsx,js,json}"
      run: bun --bun tsc --p HallOfFame/UI --noEmit
    biome:
      glob: "*.{ts,tsx,js,json}"
      run: bun biome check --no-errors-on-unmatched --files-ignore-unknown=true {staged_files}
