pre-commit:
  commands:
    check:
      root: HallOfFame/UI
      glob: "*.{ts,tsx,json}"
      run: bun tsc --noEmit && bun biome check --no-errors-on-unmatched --files-ignore-unknown=true {staged_files}
