pre-commit:
  commands:
    tsc:
      glob: "*.{ts,tsx,js,json}"
      run: bun --bun tsc --p HallOfFame/UI --noEmit
    biome:
      glob: "*.{ts,tsx,js,json}"
      run: bun biome check --no-errors-on-unmatched --files-ignore-unknown=true {staged_files}
