pre-commit:
    commands:
        check:
            root: HallOfFame/UI
            glob: "*.{ts,tsx,json}"
            run: npx biome check --no-errors-on-unmatched --files-ignore-unknown=true {staged_files}
