#!/usr/bin/env bash
# Sets up the Cities: Skylines II modding toolchain on Linux, where the in-game installer cannot run.
#
# Builds run on native .NET. Only the Windows-only post-processor and publisher run under the
# game's own Proton, reached through wrapper scripts. The Unity mod project is opened once by a
# Linux Unity editor (inside the Flatpak Unity Hub's sandbox when present, for its license), while
# the Windows editor of the same version is installed into the Proton prefix only for the IL
# post-processor runner the post-processor drives.
#
# Idempotent: rerun it after a game update changes the toolchain.
# Needs the game installed through Steam and launched once, and the game closed.
# Environment: STEAM_ROOT (default ~/.local/share/Steam).

set -euo pipefail

steam=${STEAM_ROOT:-$HOME/.local/share/Steam}
game="$steam/steamapps/common/Cities Skylines II"
compat="$steam/steamapps/compatdata/949230"
pfx="$compat/pfx"
user_data="$pfx/drive_c/users/steamuser/AppData/LocalLow/Colossal Order/Cities Skylines II"
game_tooling="$game/Cities2_Data/Content/Game/.ModdingToolchain"
tool_path="$user_data/.cache/Modding"
ump="$tool_path/UnityModsProject"
downloads="$HOME/.cache/cs2-modding-linux"
env_file="$HOME/.config/environment.d/60-cs2-modding.conf"
hub_flatpak=com.unity.UnityHub
dotnet6_version=6.0.36

step() {
  printf '\n\e[1;34m==> %s\e[0m\n' "$*"
}

die() {
  printf '\e[1;31merror:\e[0m %s\n' "$*" >&2
  exit 1
}

# Downloads to a .part file first, so an interrupted download is never mistaken for a complete one.
fetch() {
  local url=$1 file=$2

  if [[ -f $file ]]; then
    return
  fi

  mkdir -p "$(dirname "$file")"
  curl -fL --progress-bar -C - -o "$file.part" "$url"
  mv "$file.part" "$file"
}

win_path() {
  local path=${1//\//\\}

  printf 'Z:%s' "$path"
}

[[ -d $game_tooling ]] || die "No toolchain found in '$game_tooling', is the game installed?"
[[ -f $compat/version ]] || die "No Proton prefix in '$compat', launch the game once first."
! pgrep -f 'Cities2\.exe' >/dev/null || die 'Close the game first.'

# Use the Proton that owns the prefix, so nothing here upgrades it behind the game's back.
prefix_version=$(<"$compat/version")
proton=
for candidate in "$steam"/steamapps/common/Proton* "$steam"/compatibilitytools.d/*; do
  if grep -qs "^CURRENT_PREFIX_VERSION=\"$prefix_version\"" "$candidate/proton"; then
    proton=$candidate
    break
  fi
done
[[ -n $proton ]] || die "No installed Proton matches the prefix version $prefix_version."

wine() {
  WINEPREFIX="$pfx" WINEDEBUG=-all "$proton/files/bin/wine" "$@"
}

wineserver_wait() {
  WINEPREFIX="$pfx" "$proton/files/bin/wineserver" -w
}

# The editor version and changeset come from the game's own Unity project, so they follow updates.
read -r unity_version unity_changeset < <(
  unzip -p "$game_tooling/UnityModsProject.zip" '*ProjectVersion.txt' | tr -d '\r' |
    sed -n 's/^m_EditorVersionWithRevision: \([^ ]*\) (\([0-9a-f]*\))$/\1 \2/p'
) || true
[[ -n ${unity_version:-} ]] || die 'Could not read the Unity version from UnityModsProject.zip.'
unity_downloads="https://download.unity3d.com/download_unity/$unity_changeset"

step "Toolchain files into $tool_path"
mkdir -p "$tool_path" "$user_data/Mods"
cp -r "$game_tooling/ModPostProcessor" "$game_tooling/ModPublisher" "$game_tooling/Mod.targets" \
  "$tool_path/"

# Mod.props reads each CSII_* variable from the Windows user scope, which is always empty on
# Linux: strip the scope argument so it reads the process environment instead.
sed "s/, 'EnvironmentVariableTarget.User'//g" "$game_tooling/Mod.props" >"$tool_path/Mod.props"

# The Mod.targets stages call these wrappers with Linux paths: they translate every absolute path
# argument to its Z: drive form and run the Windows tool under the game's Proton.
# stderr is an MSBuild error, so Proton's wineserver startup notice is filtered out of it.
for tool in ModPostProcessor ModPublisher; do
  cat >"$tool_path/$tool/$tool.sh" <<EOF
#!/usr/bin/env bash
# Generated by scripts/setup-linux-toolchain.sh, rerun it instead of editing this file.
set -euo pipefail

# Wine hands the Linux environment to Windows processes, and the Windows .NET host would follow the
# Linux SDK's DOTNET_ROOT into a runtime it cannot load.
unset "\${!DOTNET_@}" "\${!MSBuild@}" "\${!MSBUILD@}"

args=()
for arg in "\$@"; do
  [[ \$arg == /* ]] && arg="Z:\${arg//\\//\\\\}"
  args+=("\$arg")
done
export WINEPREFIX='$pfx' WINEDEBUG=-all
exec '$proton/files/bin/wine' '$tool_path/$tool/$tool.exe' "\${args[@]}" \\
  2> >(grep -v '^wineserver: ' >&2)
EOF
  chmod +x "$tool_path/$tool/$tool.sh"
done

step "Windows .NET $dotnet6_version runtime in the Proton prefix (runs the post-processor)"
dotnet_dir="$pfx/drive_c/Program Files/dotnet"
if [[ -d $dotnet_dir/shared/Microsoft.NETCore.App/$dotnet6_version ]]; then
  echo 'Already installed.'
else
  zip="$downloads/dotnet-runtime-$dotnet6_version-win-x64.zip"
  fetch "https://builds.dotnet.microsoft.com/dotnet/Runtime/$dotnet6_version/dotnet-runtime-$dotnet6_version-win-x64.zip" "$zip"
  mkdir -p "$dotnet_dir"
  unzip -qo "$zip" -d "$dotnet_dir"
  rm "$zip"
fi

step "Windows Unity $unity_version editor in the Proton prefix (its IL post-processor runner)"
win_unity_dir="C:\\Program Files\\Unity $unity_version"
win_unity="$pfx/drive_c/Program Files/Unity $unity_version"
if [[ -f $win_unity/Editor/Data/Tools/ilpp/Unity.ILPP.Runner/Unity.ILPP.Runner.exe ]]; then
  echo 'Already installed.'
else
  installer="$downloads/UnitySetup64-$unity_version.exe"
  fetch "$unity_downloads/Windows64EditorInstaller/UnitySetup64-$unity_version.exe" "$installer"

  # The same silent install the in-game toolchain runs. NSIS wants /D= unquoted even with spaces,
  # which only a raw cmd command line preserves.
  wine cmd /c "$(win_path "$installer") /S /D=$win_unity_dir"
  wineserver_wait
  [[ -f $win_unity/Editor/Unity.exe ]] || die "The Unity installer left no editor in '$win_unity'."
  rm "$installer"
fi

# The post-processor locates the editor through this installer key, then reads the version from
# the user scope, which under Proton is the prefix registry.
wine reg add "HKLM\\SOFTWARE\\Unity Technologies\\Installer\\Unity $unity_version" \
  /v 'Location x64' /t REG_SZ /d "$win_unity_dir" /f >/dev/null
wine reg add 'HKCU\Environment' /v CSII_UNITYVERSION /t REG_SZ /d "$unity_version" /f >/dev/null

step "Linux Unity $unity_version editor (opens the Unity mod project)"
linux_unity="$HOME/Unity/Hub/Editor/$unity_version"
if [[ -x $linux_unity/Editor/Unity ]]; then
  echo 'Already installed.'
else
  archive="$downloads/Unity-$unity_version.tar.xz"
  fetch "$unity_downloads/LinuxEditorInstaller/Unity-$unity_version.tar.xz" "$archive"
  mkdir -p "$linux_unity"
  tar -xJf "$archive" -C "$linux_unity"
  rm "$archive"
fi

step "Unity mod project in $ump"
zip_hash=$(sha256sum "$game_tooling/UnityModsProject.zip" | cut -d' ' -f1)
if [[ -f $ump/Library/ScriptAssemblies/Unity.Entities.CodeGen.dll &&
  $(cat "$ump/.zip-sha256" 2>/dev/null) == "$zip_hash" ]]; then
  echo 'Up to date.'
else
  rm -rf "$ump"

  # The archive stores backslash paths, which unzip turns into directories with a warning.
  unzip -q "$game_tooling/UnityModsProject.zip" -d "$ump" 2>/dev/null || [[ -d $ump/Packages ]]

  # Opening the project once resolves its packages and compiles the IL post-processors into
  # Library/. A Flatpak Hub keeps its license inside its sandbox, so the editor runs there too.
  unity=("$linux_unity/Editor/Unity")
  if flatpak info "$hub_flatpak" >/dev/null 2>&1; then
    unity=(flatpak run --command="$linux_unity/Editor/Unity" "$hub_flatpak")
  fi

  log="$downloads/UnityModsProject.log"
  mkdir -p "$downloads"
  if ! "${unity[@]}" -batchmode -nographics -quit -projectPath "$ump" -logFile "$log" ||
    [[ ! -f $ump/Library/ScriptAssemblies/Unity.Entities.CodeGen.dll ]]; then
    tail -n 30 "$log" >&2
    die "Unity failed to open the mod project, full log in $log"
  fi

  echo "$zip_hash" >"$ump/.zip-sha256"
fi

entities_dir=$(find "$ump/Library/PackageCache" -maxdepth 1 -name 'com.unity.entities@*' -print -quit)
[[ -n $entities_dir ]] || die 'The Unity mod project resolved no com.unity.entities package.'
entities_version=${entities_dir##*@}

step "Environment variables in $env_file"
mkdir -p "$(dirname "$env_file")"
cat >"$env_file" <<EOF
# Generated by scripts/setup-linux-toolchain.sh: the Linux counterpart of the user environment
# variables the in-game toolchain installer writes on Windows.
CSII_INSTALLATIONPATH="$game"
CSII_MANAGEDPATH="$game/Cities2_Data/Managed"
CSII_MSCORLIBPATH="$game/Cities2_Data/Managed/mscorlib.dll"
CSII_USERDATAPATH="$user_data"
CSII_LOCALMODSPATH="$user_data/Mods"
CSII_TOOLPATH="$tool_path"
CSII_UNITYMODPROJECTPATH="$ump"
CSII_UNITYVERSION="$unity_version"
CSII_ENTITIESVERSION="$entities_version"
CSII_MODPOSTPROCESSORPATH="$tool_path/ModPostProcessor/ModPostProcessor.sh"
CSII_MODPUBLISHERPATH="$tool_path/ModPublisher/ModPublisher.sh"
EOF
cat "$env_file"

step 'Done'
echo 'Log out and back in so every app sees the variables, or load them into this shell with:'
echo "  set -a; . '$env_file'; set +a"
